name: zc FTP server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: zc FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: zc.5ibc.cn
          username: ftpadmin
          password: 123456
          local-dir: ./
          server-dir: /htdocs/